### ISSUE TITLE
picgo安装该插件上传失败了，400错误

### ISSUE THREAD

**Issue by huyongnd** [xizeyoupan/picgo-plugin-UCloud-uploader#1]
设置没问题，报错400.
<img width="375" alt="image" src="https://user-images.githubusercontent.com/112535394/221772144-d55a80e2-bf4a-48e9-9b4c-4b556de34f70.png">
日志也没啥有用的信息：
<img width="642" alt="image" src="https://user-images.githubusercontent.com/112535394/221772214-9f7d74d8-ad4d-4030-abf3-642c946e625a.png">

**Comment by xizeyoupan** [comment]
如果配置正确的话，上传应该是成功的，能在ucloud中看到。之前存在的问题是成功后没显示信息，现已修复。但code 400可能说明配置有误。建议更新下插件重试，如还有问题请贴一下配置（不要暴露api key）
